### ISSUE TITLE
About the component of inverse reinforcement learning

### ISSUE THREAD

**Issue by momo1986** [d1024choi/traj-pred-irl#2]
Hello, I am very interested in your idea that inverse reinforcement learning is used for regularization.

Thanks for sharing.

Could you point out that where is the module for RL?

I want to understand your idea better via source code.

Thanks & Regards!

**Comment by d1024choi** [comment]
> Hello, I am very interested in your idea that inverse reinforcement learning is used for regularization.
> 
> Thanks for sharing.
> 
> Could you point out that where is the module for RL?
> 
> I want to understand your idea better via source code.
> 
> Thanks & Regards!

Thank you for your interest and sorry for my late response.

You can find in 'sdd_model.py' or' crowd_model.py' that, during the past trajectory and scene context encoding process, reward values (one from the ground-truth past position and the other from the estimated position) are calculated. The calculated reward values are used to train both rnn encoder (for trajectory prediction) and reward function.

**Comment by d1024choi** [comment]
.
